USE TOBBYLAND;

INSERT INTO SEMESTER (SEMESTER_TITLE)
VALUES ('벙커 데이터');

INSERT INTO SEMESTER (SEMESTER_TITLE)
VALUES ('13-1학기');

INSERT INTO SEMESTER (SEMESTER_TITLE)
VALUES ('13-2학기');

INSERT INTO SEMESTER (SEMESTER_TITLE)
VALUES ('14-1학기');

INSERT INTO SEMESTER (SEMESTER_TITLE)
VALUES ('14-2학기');

INSERT INTO SEMESTER (SEMESTER_TITLE)
VALUES ('15-1학기');

INSERT INTO SEMESTER (SEMESTER_TITLE)
VALUES ('15-2학기');