USE TOBBYLAND;

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '1', '1');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '2', '2');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '3', '3');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '4', '4');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '5', '5');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '6', '6');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '7', '7');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '8', '8');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '9', '9');

INSERT INTO LECTURESUB (LECTURE_ID, MEMBER_ID, KIND, TITLE, CONTENTS)
VALUES (465, 'ADMIN', 2, '10', '10');